### ISSUE TITLE
Possible typo in an example call

### ISSUE THREAD

**Issue by foreverluiscastro** [learn-co-curriculum/python-p3-comprehensions-and-generators#3]
### Canvas Link

https://learning.flatironschool.com/courses/6049/assignments/195252?module_item_id=439019

### Concern

In the lab when you describe the functionality of the make_exclamation function at the end of the README, the call to the function looks like:

```make_exclamation("Hello", "I'm doing great", "Python is fun")```

when the call that I wrote to properly call the function looks like:

```make_exclamation(["Hello", "I'm doing great", "Python is fun"])```

putting the broken up string inside of a list. Is this a typo or am I missing something?

**Comment by professor-ben** [comment]
Hi Luis, I seem to have fixed this a while ago and never closed it. Thanks for raising the issue!

-Ben
