### ISSUE TITLE
Lots of Googling

### ISSUE THREAD

**Issue by bdenney** [learn-co-curriculum/python-p3-comprehensions-and-generators#7]
### Canvas Link

https://learning.flatironschool.com/courses/6049/assignments/195252?module_item_id=439019

### Concern

This lab felt like I had to google a lot to get things to work. I could see this being frustrating to students.

**Comment by professor-ben** [comment]
I've pushed up a solution branch to look at- I think that it will provide some helpful context. I'm going to double check that we cover the `%` modulo operator in the fundamentals module as well.
