### ISSUE TITLE
missing part of answer

### ISSUE THREAD

**Issue by Aaidenplays** [learn-co-curriculum/python-p3-comprehensions-and-generators#8]
### Canvas Link

https://learning.flatironschool.com/courses/6049/assignments/195252?module_item_id=439019

### Concern

for the question `Which data type does a list comprehension return?` the answer shows `my_lc = [n for n in range(10)]
type(my_lc)
#`

I think the type is supposed to go after the hashtag.

**Comment by pgill97** [comment]
@professor-ben  Strange bug but fixed main and solution by escaping inline html [6896355](https://github.com/learn-co-curriculum/phase-3-comprehensions-and-generators/commit/6896355c436f6aab871c406371a943d4123d6a85). Apparently <class 'list'> gets interpreted as HTML in canvas but looks fine on the GitHub readme.
